language: clojure
dist: trusty
lein: lein
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.0/elasticsearch-2.4.0.deb
    && sudo dpkg -i --force-confnew elasticsearch-2.4.0.deb && sudo service elasticsearch
    restart
  - mkdir -p $HOME/.lein
  - touch $HOME/.lein/profiles.clj
  - echo '{:user {:dependencies [[org.clojure/clojure "1.8.0"] [potemkin "0.4.5"]]}}'
    > $HOME/.lein/profiles.clj
before_script:
  - psql -c 'CREATE DATABASE kulu_backend_test;' -U postgres
  - psql -d kulu_backend_test -c 'CREATE extension "uuid-ossp";' -U postgres
  - sleep 10
env:
  global:
    - PGPORT = 6666 DATABASE_URL = postgres://$USER:@localhost:$PGPORT/kulu_backend_test
    - secure: ptDjxKXVfoGWiaOh+3xCFo/rSV/JCXRRUvr6hZkRaYosUvr9BGdvBn6CLUPkKonMfe0Om7EKZCfWDnrtC77r8JXNCbt/dAx3Au8u690acFjw+Rr7GX6klR/nkDGzjrQOgFYf1ueKqEgxbJN/wd8FhfgimGKEjzU7r8FxlY+KIDWdsTE6Ptfzfle9wZkjA1RQQiafZgConyyTxJiF2eqS77q7z3RVbPXJl2A7CLYRu6W9rjBsGHDoXD2XFH5YVrvnHFcqikElqfjzMJZ/nF+yDiWWRgVlRiDRHaromoGGLI73VsglQEAWvFhlezOp8WWA4uwXO4805NYL7p0s7XH7+KsHB6Keqo3AuotBUm6O8xHVP/u6qIqRbResaLwaLeMcMpns4+fg4GetbZYOqc3HQXdXq3e57KbTnyoHlLhALlkibhK1e9RkJ3kkdov9fM3sKJZTULHlELqPOky5NKMH7c5+GmPMzTaJm2ga6MxkgkiiTaa0BdFwM1iebGAX65TOYY7/0mLOyPtTTvhOCBqOxElhMWrEqwRI9TKpwLwDae2khdhYKiol8TZL7n9RDpvAuCU073K23/5dspN1ha1O6bZQtx7Ud42daJG2pPEsFIi+448taNSsZ+UdrInln6BuhrL6eVcZaiiJcgSzLz/4vSIStdaLx+iravYzoT0Rx0U=
script: lein test
branches:
  only:
    - ansible
notifications:
  email:
    on_success: never
    on_failure: never
services:
  - elasticsearch
addons:
  postgresql: '9.6'
  hosts: 165.22.213.15
before_deploy:
  - openssl aes-256-cbc -K $encrypted_2ffb742f6491_key -iv $encrypted_2ffb742f6491_iv
    -in kulu.pem.enc -out kulu.pem -d
  - chmod 600 kulu.pem
deploy:
  provider: script
  script: ansible-playbook kulu.yml -u $ANSIBLE_USER -e "ansible_sudo_pass=$ANSIBLE_SUDO_PASS"
  on:
    branch: ansible
