language: clojure
dist: trusty
lein: lein
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.0/elasticsearch-2.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.0.deb && sudo service elasticsearch restart
  - mkdir -p $HOME/.lein
  - touch $HOME/.lein/profiles.clj
  - echo '{:user {:dependencies [[org.clojure/clojure "1.8.0"] [potemkin "0.4.5"]]}}' > $HOME/.lein/profiles.clj
before_script:
  - psql -c 'CREATE DATABASE kulu_backend_test;' -U postgres
  - psql -d kulu_backend_test -c 'CREATE extension "uuid-ossp";' -U postgres
  - sleep 10
env:
  global:
    PGPORT = 6666
    DATABASE_URL = postgres://$USER:@localhost:$PGPORT/kulu_backend_test
script: lein test
branches:
  only:
    - travis-ci
notifications:
  email:
    on_success: never
    on_failure: never
services:
  - elasticsearch
addons:
  postgresql: "9.6"